# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers :
        default :
            web_path :
                web_root: "%kernel.project_dir%/public"
                cache_prefix: '%app.user.profile.url%/cache'

    filter_sets :
        cache : ~

        # the name of the "filter set"
        thumb_400 :

            # adjust the image quality to 75%
            quality : 75

            # list of transformations to apply (the "filters")
            filters :
                relative_resize:

                    # given 50x40px, output 75x60px using "heighten" option
                    heighten: 400

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail  : { size : [400, 400], mode : outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background : { size : [400, 400], position : center, color : '#000000' }

        thumb_100:
            quality: 75

            filters:
                relative_resize:

                    # given 50x40px, output 75x60px using "heighten" option
                    heighten: 100

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 100, 100 ], mode: outbound }
        thumb_50:
            quality: 75

            filters:
                relative_resize:

                # given 50x40px, output 75x60px using "heighten" option
                    heighten: 50

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [ 50, 50 ], mode: outbound }