twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
      - 'bootstrap_5_layout.html.twig'
      - "@PrestaImage/form/bootstrap_5.html.twig"

    globals:
        profile_url: '%app.user.profile.url%'

when@test:
    twig:
        strict_variables: true
