# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: "mariadb:10.4.24"
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3307:3306"

  adminer:
    image: "adminer"
    restart: "no"
    ports:
      - 8080:8080